CREATE TABLE Users
(username VARCHAR(256) NOT NULL PRIMARY KEY);

CREATE TABLE Buildings
(name VARCHAR(256) NOT NULL PRIMARY KEY);

CREATE TABLE Bathrooms
(bn VARCHAR(256) NOT NULL REFERENCES Buildings(name),
 floor VARCHAR(128) NOT NULL,
 gender CHAR(20) NOT NULL,
 PRIMARY KEY (bn, floor, gender));

CREATE TABLE Reviews
(reviewid INTEGER NOT NULL PRIMARY KEY,
 poopability INTEGER NOT NULL,
 cleanliness INTEGER NOT NULL,
 cryability INTEGER NOT NULL,
 overall INTEGER NOT NULL,
 comments VARCHAR(256));
